services:
  - type: web
    name: ttravel-hospitality
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ttravel-db
          property: connectionString
    autoDeploy: false

databases:
  - name: ttravel-db
    databaseName: ttravel_hospitality
    user: ttravel_user
    plan: starter