services:
  - type: web
    name: ttravel-backend-api
    env: node
    plan: starter
    buildCommand: ./build-backend.sh
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: YOUR_NEON_DATABASE_URL_HERE
      - key: CORS_ORIGIN
        value: https://your-vercel-frontend-url.vercel.app
    autoDeploy: false

# Using external Neon database - no Render database needed