services:
  - type: web
    name: ttravel-hospitality
    env: node
    plan: starter
    buildCommand: ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: YOUR_NEON_DATABASE_URL_HERE
    autoDeploy: false

# Using external Neon database - no Render database needed